theme: jekyll-theme-minimal
title: "Zofia Ahmad"
description: "PhD Student, History & Central Eurasian Studies Departments, Indiana University"
logo: /assets/img/ahmad-zofia.jpg
author: "Zofia Ahmad"
